### ISSUE TITLE
having problems replicating the demo site on Angular 6

### ISSUE THREAD

**Issue by klytron** [reyesoft/ngx-jsonapi#113]
I get the error

```
zone.js:665 Unhandled Promise rejection: Cannot read property 'driver' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'driver' of undefined
    at localforageGetItems (localforage-getitems.js:213)
    at new StoreService (ngx-jsonapi.es5.js:882)
    at _createClass (core.js:8419)
    at _createProviderInstance (core.js:8393)
    at initNgModule (core.js:8326)
    at new NgModuleRef_ (core.js:9052)
    at createNgModuleRef (core.js:9041)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:10866)
    at NgModuleFactory_.push../node_modules/@angular/core/fesm5/core.js.NgModuleFactory_.create (core.js:11583)
    at core.js:4313 TypeError: Cannot read property 'driver' of undefined
    at localforageGetItems (http://localhost:4200/vendor.js:73567:49)
    at new StoreService (http://localhost:4200/vendor.js:77594:69)
    at _createClass (http://localhost:4200/vendor.js:47241:20)
    at _createProviderInstance (http://localhost:4200/vendor.js:47215:26)
    at initNgModule (http://localhost:4200/vendor.js:47148:32)
    at new NgModuleRef_ (http://localhost:4200/vendor.js:47874:9)
    at createNgModuleRef (http://localhost:4200/vendor.js:47863:12)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (http://localhost:4200/vendor.js:49688:12)
    at NgModuleFactory_.push../node_modules/@angular/core/fesm5/core.js.NgModuleFactory_.create (http://localhost:4200/vendor.js:50405:25)
    at http://localhost:4200/vendor.js:43135:43

```

using 

```
"@angular/cli": "~6.1.5",
"ngx-jsonapi": "^2.0.0-rc.1",

```

**Comment by pablorsk** [comment]
Problem solved on `^2.0.0-rc.4` :smile:
