### ISSUE TITLE
error in ng serve

### ISSUE THREAD

**Issue by ZahraAmiri1996** [reyesoft/ngx-jsonapi#52]
Hi I got this error on ng serve:

ERROR in Error: Metadata version mismatch for module C:/Users/zahra/Desktop/Tatomic/atomic-blank-v1.0.4/node_modules/ngx-jsonapi/index.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/Users/zahra/Desktop/Tatomic/atomic-blank-v1.0.4/src/app/app.module.ts, resolving symbol AppModule in C:/Users/zahra/Desktop/Tatomic/atomic-blank-v1.0.4/src/app/app.module.ts, resolving symbol AppModule in C:/Users/zahra/Desktop/Tatomic/atomic-blank-v1.0.4/src/app/app.module.ts
    at syntaxError (C:\Users\zahra\Desktop\Tatomic\atomic-blank-v1.0.4\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (C:\Users\zahra\Desktop\Tatomic\atomic-blank-v1.0.4\node_modules\@angular\compiler\bundles\compiler.umd.js:25111:23)
    at StaticReflector.simplify (C:\Users\zahra\Desktop\Tatomic\atomic-blank-v1.0.4\node_modules\@angular\compiler\bundles\compiler.umd.js:25123:13)
    at StaticReflector.annotations (C:\Users\zahra\Desktop\Tatomic\atomic-blank-v1.0.4\node_modules\@angular\compiler\bundles\compiler.umd.js:24553:41)
    at _getNgModuleMetadata (C:\Users\zahra\Desktop\Tatomic\atomic-blank-v1.0.4\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (C:\Users\zahra\Desktop\Tatomic\atomic-blank-v1.0.4\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (C:\Users\zahra\Desktop\Tatomic\atomic-blank-v1.0.4\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Users\zahra\Desktop\Tatomic\atomic-blank-v1.0.4\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (C:\Users\zahra\Desktop\Tatomic\atomic-blank-v1.0.4\node_modules\@ngtools\webpack\src\plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\Users\zahra\Desktop\Tatomic\atomic-blank-v1.0.4\node_modules\@ngtools\webpack\src\plugin.js:495:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by pablorsk** [comment]
Usa `yarn run demo:start` :)
